Tour_Web2/Controllers/CityController.cs
using AutoMapper;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Collections.Generic;
using Tour_Web.Models;
using Tour_Web.Models.DTO;
using Tour_Web.Models.Models.VM;
using Tour_Web.Services;
using Tour_Web.Services.IServices;

namespace Tour_Web.Controllers
{
    public class CityController : Controller
    {

        private readonly ICityService _cityService;
        private readonly ICountryService _countryService;

        private readonly IMapper _mapper;

        public CityController(ICityService cityService, ICountryService countryService, IMapper mapper)
        {
            _cityService = cityService;
            _countryService = countryService;
            _mapper = mapper;
        }

        public async Task <IActionResult> IndexCity()
        {
            List<CityDTO> list = new();

            var response = await _cityService.GetAllAsync<APIResponse>();
            if(response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<CityDTO>>(Convert.ToString(response.Result));
            }
            return View(list);
        }

        public async Task<IActionResult> CreateCity()
        {
            CityCreateVM cityCreatVM = new();

            var response = await _countryService.GetAllAsync<APIResponse>();

            if (response != null && response.IsSuccess)
            {
                cityCreatVM.CountryList = JsonConvert.DeserializeObject<List<CountryDTO>>
                    (Convert.ToString(response.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
            }
            return View(cityCreatVM);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateCity(CityCreateVM model)
        {
            if (ModelState.IsValid)
            {

                var response = await _cityService.CreateAsync<APIResponse>(model.CityNumber);
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "City created successfully";
                    return RedirectToAction(nameof(IndexCity));
                }
                else
                {
                    if(response.ErrorMessages.Count>0)
                    {
                        ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());
                    }
                }
            }

            var resp = await _countryService.GetAllAsync<APIResponse>();
            if (resp != null && resp.IsSuccess)
            {
                model.CountryList = JsonConvert.DeserializeObject<List<CountryDTO>>
                    (Convert.ToString(resp.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    }); ;
            }
            return View(model);
        }




        public async Task<IActionResult> UpdateCity(int cityNumber)
        {
            CityUpdateVM cityVM = new();

            var response = await _cityService.GetAsync<APIResponse>(cityNumber);
            if (response != null && response.IsSuccess)
            {
                CityDTO model = JsonConvert.DeserializeObject<CityDTO>(Convert.ToString(response.Result));
                cityVM.CityNumber =_mapper.Map<CityUpdateDTO>(model);
            }

            response = await _countryService.GetAllAsync<APIResponse>();
            if (response != null && response.IsSuccess)
            {
                cityVM.CountryList = JsonConvert.DeserializeObject<List<CountryDTO>>
                    (Convert.ToString(response.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    }); 
                return View(cityVM);
            }

            return NotFound();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateCity(CityUpdateVM model)
        {

            if (ModelState.IsValid)
            {
                var response = await _cityService.UpdateAsync<APIResponse>(model.CityNumber);
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Updated successfully";
                    return RedirectToAction(nameof(IndexCity));
                }
                else
                {
                    if(response.ErrorMessages.Count>0)
                    {
                        ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());
                    }
                }
            }
            var resp = await _countryService.GetAllAsync<APIResponse>();
            if (resp != null && resp.IsSuccess)
            {
                model.CountryList = JsonConvert.DeserializeObject<List<CountryDTO>>
                    (Convert.ToString(resp.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });

            }


            return View(model);

        }



        public async Task<IActionResult> DeleteCity(int cityNumber)
        {
            CityDeleteVM cityVM = new();

            var response = await _cityService.GetAsync<APIResponse>(cityNumber);
            if (response != null && response.IsSuccess)
            {
                CityDTO model = JsonConvert.DeserializeObject<CityDTO>(Convert.ToString(response.Result));
                cityVM.CityNumber = model;
            }

            response = await _countryService.GetAllAsync<APIResponse>();
            if (response != null && response.IsSuccess)
            {
                cityVM.CountryList = JsonConvert.DeserializeObject<List<CountryDTO>>
                    (Convert.ToString(response.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
                return View(cityVM);
            }


            return NotFound();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteCity(CityDeleteVM model)
        {

            var response = await _cityService.DeleteAsync<APIResponse>(model.CityNumber.CountryID);
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Deleted successfully";
                return RedirectToAction(nameof(IndexCity));
            }
            return View(model);
        }


    }
}

Tour_Web2/Controllers/CountryController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Tour_Web.Models;
using Tour_Web.Models.DTO;
using Tour_Web.Services.IServices;

namespace Tour_Web.Controllers
{
    public class CountryController : Controller
    {

        private readonly ICountryService _countryService;
        private readonly IMapper _mapper;

        public CountryController(ICountryService countryService, IMapper mapper)
        {
            _countryService = countryService;
            _mapper = mapper;
        }

        public async Task <IActionResult> IndexCountry()
        {
            List<CountryDTO> list = new();

            var response = await _countryService.GetAllAsync<APIResponse>();
            if(response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<CountryDTO>>(Convert.ToString(response.Result));
            }
            return View(list);
        }

        public async Task<IActionResult> CreateCountry()
        {
            
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateCountry(CountryCreateDTO model)
        {
            
            if(ModelState.IsValid)
            { 
                var response = await _countryService.CreateAsync<APIResponse>(model);
                 if (response != null && response.IsSuccess)
                 {
                    TempData["success"] = "Country created successfully";
                    return RedirectToAction(nameof(IndexCountry));

                   }
                }
            return View(model);
        }


        public async Task<IActionResult> UpdateCountry(int countryId)
        {
            var response = await _countryService.GetAsync<APIResponse>(countryId);
            if (response != null && response.IsSuccess)
            {
                CountryDTO model = JsonConvert.DeserializeObject<CountryDTO>(Convert.ToString(response.Result));
                return View(_mapper.Map<CountryUpdateDTO>(model));
            }

            return NotFound();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateCountry(CountryUpdateDTO model)
        {

            if (ModelState.IsValid)
            {
                var response = await _countryService.UpdateAsync<APIResponse>(model);
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Updated successfully";
                    return RedirectToAction(nameof(IndexCountry));
                }
            }
            return View(model);
        }


        public async Task<IActionResult> DeleteCountry(int countryId)
        {
            var response = await _countryService.GetAsync<APIResponse>(countryId);
            if (response != null && response.IsSuccess)
            {
                CountryDTO model = JsonConvert.DeserializeObject<CountryDTO>(Convert.ToString(response.Result));
                return View(model);
            }

            return NotFound();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteCountry(CountryDTO model)
        {

                var response = await _countryService.DeleteAsync<APIResponse>(model.Id);
                if (response != null && response.IsSuccess)
                {
                TempData["success"] = "Delete successfully";
                return RedirectToAction(nameof(IndexCountry));
                }
             return View(model);
        }

    }
}

Tour_Web2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tour_Web</title>
    <link rel="stylesheet" href="~/css/bootstrap.css"  />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Tour_Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark  box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Tour_Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="IndexCountry">Country</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="IndexCity">City</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class=" footer text-muted">
        <div class="container">
            &copy; 2024 - Tour_Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Tour_Web2/Views/Shared/_Notification.cshtml
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
@if (TempData["success"] != null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'top-end',
            icon: 'success',
            title: '@TempData["success"]',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true
        })
    </script>
}
@if (TempData["error"] != null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'top-end',
            icon: 'error',
            title: '@TempData["error"]',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true
        })
    </script>
}
